# https://github.com/knazeri/edge-connect/blob/master/src/config.py
# hydra's settings ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
defaults:
  - _self_
  # - override hydra/hydra_logging: disabled
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .

data:
  INPUT_DIR: data/submission/clustering/human/3_7
  OUTPUT_DIR: data/submission/cluster_fraction/human/3_7
  META: data/submission/meta/human_tma_20220112.csv

cluster:
  ignore: [3, 6, 7, 8, 12, 16, 21, 26, 27, 29, 30]
