# @package models
data:
  INPUT_DIR_CLUSTER: data/submission/clustering/human/3_7
  INPUT_DIR_SHANNON: data/submission/feature/human/shannon/kernel_20
  OUTPUT_DIR: data/submission/shannon_by_status/human/3_7
