version: 1
formatters:
  console:
    format: "%(asctime)s - %(levelname)s - %(filename)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
root:
  handlers: [console]

disable_existing_loggers: false
