hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      console:
        format: '%(asctime)s - %(levelname)s - %(filename)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: console
        stream: ext://sys.stdout
    root:
      handlers:
      - console
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - models=predict_human
  job:
    name: predict
    chdir: null
    override_dirname: models=predict_human
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.2.0
    version_base: '1.2'
    cwd: /work/Submission/kmeans_clustering
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /work/Submission/kmeans_clustering/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      models: predict_human
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: custom
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
models:
  train: false
  data:
    INPUT_DIR: data/submission/cropped/human/liver/14/slide
    MODEL_DIR: data/submission/clustering/mouse
    OUTPUT_DIR: data/submission/clustering/human
  clustering:
    N_SAMPLE: 1000000
    N_CLUSTERS: 30
common:
  SCALE: 0.5
  SEED: 20220202
mbf:
  intensity: true
  edges: false
  texture: true
  sigma_min: 6
  sigma_max: 20
  channel_axis: 2
mbf_experiments:
  sigma_minmax_pairs:
  - - 3
    - 7
  - - 3
    - 10
  - - 3
    - 15
  - - 4
    - 7
  - - 4
    - 10
  - - 4
    - 15
  - - 5
    - 7
  - - 5
    - 10
  - - 5
    - 15
  - - 6
    - 20
