# https://github.com/knazeri/edge-connect/blob/master/src/config.py
# hydra's settings ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
defaults:
  - _self_
  # - override hydra/hydra_logging: disabled
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .

data:
  INPUT_DIR_RAW: data/submission/cropped/mouse/liver/15/slide
  INPUT_DIR_CLUSTER: data/submission/clustering/mouse/3_7
  OUTPUT_DIR: data/submission/tumor_fraction/mouse/3_7

cluster:
  ignore: [3, 6, 7, 8, 12, 16, 21, 26, 27, 29, 30]

annotation:
  normals: [[2], [1], [], [1], [2]]
  abnormals: [[1], [], [1], [2], [1]]
