# https://github.com/knazeri/edge-connect/blob/master/src/config.py
# hydra's settings ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
defaults:
  - species: mouse
  - _self_
  # - override hydra/hydra_logging: disabled
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .

shannon:
  tile_size: 512   # 1000だとGPUのメモリが不足する
  kernel_size: 20
  multichannel: true
